"""Register and unregister clowk's hooks, per host.

Hooks declared in a Claude Code plugin manifest do not fire in build 2.1.202 -- they load and
are counted, but never execute. Only settings-registered hooks run. clowk therefore ships NO
manifest hooks at all and this module is the single registration path, which also makes
double-registration impossible.

Merges into whatever is already there. A real user's settings.json commonly already has hooks
on these same events, so replacing an event array would silently break their setup. Backs up
first, refuses rather than guesses on an unparseable file, and writes atomically.
"""
import json
import os
import shutil
import sys
import stat

TARGETS = {
    "claude-code": {
        "settings": os.path.join("~", ".claude", "settings.json"),
        "prompt_event": "UserPromptSubmit",
        "tool_event": "PreToolUse",
        "tool_matcher": "Bash|Read",
    },
    "codex": {
        "settings": os.path.join("~", ".codex", "hooks.json"),
        "prompt_event": "UserPromptSubmit",
        "tool_event": "PreToolUse",
        "tool_matcher": "Bash",
    },
    "gemini-cli": {
        "settings": os.path.join("~", ".gemini", "settings.json"),
        "prompt_event": "BeforeAgent",
        "tool_event": "BeforeTool",
        "tool_matcher": None,
    },
}

MARKER = "clowk"


def settings_path(host):
    return os.path.expanduser(TARGETS[host]["settings"])


def is_clowk_entry(entry):
    """True if this hook entry is one of ours -- used by uninstall to remove only our own."""
    if not isinstance(entry, dict):
        return False
    command = entry.get("command")
    return isinstance(command, str) and MARKER in command and (
        "hook_prompt.py" in command or "hook_pretool.py" in command)


def _command(root, script, host):
    """The hook command a host will run.

    The interpreter is the one running this install, not the literal name "python3": on Windows
    there is no python3 on PATH -- it is python, or the py launcher, or a Microsoft Store alias
    stub that opens the Store instead of running anything. Registering "python3" there produced a
    hook that could never execute while install still reported success. sys.executable is an
    absolute path to an interpreter that demonstrably works, because it is the one you just used.
    """
    interpreter = sys.executable or "python3"
    return '"%s" "%s" --host %s' % (interpreter, os.path.join(root, "clowk", script), host)


# A user-level slash command, so `/clowk` works without the plugin. A plugin command is always
# namespaced as <plugin>:<command>, which makes the plugin's copy `/clowk:clowk`; a file in
# ~/.claude/commands is not namespaced. This one is GENERATED rather than copied, because
# commands/clowk.md resolves ${CLAUDE_PLUGIN_ROOT}, which is set only for plugin commands -- copying
# it produced `python3 "/clowk/cli.py"` and an unknown-command error. Writing the interpreter and
# path in directly is the same trick the hook commands already use.
COMMAND_MARKER = "<!-- generated by clowk install -->"
COMMAND_BODY = """---
description: Manage clowk-captured credentials (list, clear, rename, uses, allow)
argument-hint: [list | clear NAME | rename OLD NEW | uses [NAME] | allow PATTERN]
allowed-tools: Bash
---
%s
Result of the clowk management CLI:

!`%s "%s" $ARGUMENTS`

Present the result above to the user clearly. With no arguments the CLI prints its usage summary
and exits 1 -- point the user at `/clowk list` to see what is stored.

Note for the assistant: `clowk add` and `clowk set` deliberately prompt for the value on a
terminal and cannot be driven from here -- tell the user to run them in their own shell.
"""


def command_path():
    """Where the unnamespaced /clowk command lives. CLOWK_COMMANDS overrides it, for tests.

    An override rather than letting tests reassign HOME: on Windows expanduser("~") reads
    USERPROFILE, not HOME, so setting HOME redirected nothing and the tests wrote into the real
    user profile -- then failed on the directory already existing. CLOWK_VAULT and CLOWK_DENY
    already work this way, so this is the established pattern here.
    """
    override = os.environ.get("CLOWK_COMMANDS")
    if override:
        return override
    return os.path.expanduser(os.path.join("~", ".claude", "commands", "clowk.md"))


def install_command(root):
    """Write ~/.claude/commands/clowk.md. Returns the path, or None if we must not touch it."""
    path = command_path()
    if os.path.exists(path):
        try:
            with open(path, encoding="utf-8") as f:
                if COMMAND_MARKER not in f.read():
                    return None      # someone else's /clowk command; never clobber it
        except (IOError, OSError, UnicodeDecodeError):
            return None
    parent = os.path.dirname(path)
    if parent:
        try:
            os.makedirs(parent)
        except OSError:
            pass          # already there, which is the normal case
    cli = os.path.join(root, "clowk", "cli.py")
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8", newline="") as f:
        f.write(COMMAND_BODY % (COMMAND_MARKER, sys.executable or "python3", cli))
    os.replace(tmp, path)
    return path


def uninstall_command():
    """Remove the generated command file. Leaves a hand-written one alone. Returns True if removed."""
    path = command_path()
    if not os.path.exists(path):
        return False
    try:
        with open(path, encoding="utf-8") as f:
            if COMMAND_MARKER not in f.read():
                return False
    except (IOError, OSError, UnicodeDecodeError):
        return False
    os.remove(path)
    return True


def _load(path):
    if not os.path.exists(path):
        return {}, False
    # encoding="utf-8" explicitly: settings.json is UTF-8 (hosts write it with JS JSON.stringify,
    # which emits non-ASCII raw), but open() with no encoding uses the locale codec -- the ANSI
    # codepage on stock Windows. That read either mangled a valid file into permanent mojibake or
    # refused it with a raw codec error blaming JSON that was never invalid.
    try:
        with open(path, encoding="utf-8") as f:
            text = f.read()
    except UnicodeDecodeError:
        raise ValueError(
            "%s is not UTF-8. clowk will not modify it -- re-save it as UTF-8, then retry." % path)
    if not text.strip():
        return {}, True
    try:
        data = json.loads(text)
    except ValueError:
        raise ValueError(
            "%s is not valid JSON. clowk will not modify it -- fix or move the file, then retry." % path)
    if not isinstance(data, dict):
        raise ValueError("%s does not contain a JSON object. clowk will not modify it." % path)
    return data, True


def _save(path, data):
    parent = os.path.dirname(path)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    try:
        mode = stat.S_IMODE(os.stat(path).st_mode)
    except OSError:
        mode = 0o600  # creating it: start closed rather than at whatever the umask allows
    tmp = path + ".tmp"
    # os.replace hands the file a new inode, so the mode has to be carried over deliberately --
    # otherwise a settings.json the user chmod'd to 0600 came back 0644, widened by the tool that
    # exists for credential hygiene. The temp file is created closed and only then widened to the
    # recorded mode: a crash mid-write must not leave a readable copy of an `env` block behind.
    # Match the file's existing line endings. Python's text layer translates "\n" to "\r\n" on
    # Windows unless newline="" says otherwise -- O_BINARY on the descriptor does not stop it,
    # because the translation happens above it in TextIOWrapper. Uninstall therefore rewrote every
    # line ending in the user's settings file, which is not "leaves everything else exactly as you
    # wrote it". newline="" disables translation; matching what was already there preserves a
    # CRLF file too, so the round-trip is byte-exact on every platform either way.
    crlf = False
    try:
        with open(path, "rb") as existing:
            crlf = b"\r\n" in existing.read()
    except (IOError, OSError):
        pass
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_BINARY", 0)
    fd = os.open(tmp, flags, 0o600)
    # ensure_ascii=False keeps the host's own non-ASCII text exactly as it wrote it, so uninstall
    # can still put the file back byte for byte. It is safe only because the encoding is pinned.
    text = json.dumps(data, indent=2, ensure_ascii=False)
    if crlf:
        text = text.replace("\n", "\r\n")
    with os.fdopen(fd, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    try:
        os.chmod(tmp, mode)  # honours only the read-only bit on Windows
    except OSError:
        pass
    os.replace(tmp, path)


def _backup(path):
    if not os.path.exists(path):
        return None
    for n in range(1, 100):
        candidate = "%s.clowk-backup-%d" % (path, n)
        if not os.path.exists(candidate):
            shutil.copy2(path, candidate)
            return candidate
    return None


def _add(hooks, event, matcher, command, path):
    """Append our entry to `event`, reusing a group with the same matcher. Returns 1 if added."""
    groups = hooks.setdefault(event, [])
    if not isinstance(groups, list):
        # Overwriting it would silently delete whatever the user had on this event while
        # reporting success. Refuse, like the unparseable-file and non-object-hooks cases.
        raise ValueError(
            "%s has a %r hook entry that is not an array. clowk will not modify it -- "
            "fix or move the file, then retry." % (path, event))
    for group in groups:
        if not isinstance(group, dict):
            continue
        entries = group.get("hooks", [])
        if not isinstance(entries, list):
            # Absent is fine (a matcher-only group); a dict, string or number where the array
            # belongs is not. Iterating it or appending to it raised TypeError/AttributeError,
            # neither of which cmd_install catches, so `clowk install` printed a traceback.
            # Refuse, like the unparseable-file and non-list-event cases.
            raise ValueError(
                "%s has a %r hook group whose 'hooks' value is not an array. clowk will not "
                "modify it -- fix or move the file, then retry." % (path, event))
        for entry in entries:
            if isinstance(entry, dict) and entry.get("command") == command:
                return 0  # already registered -- idempotent
    entry = {"type": "command", "command": command}
    for group in groups:
        if isinstance(group, dict) and group.get("matcher") == matcher:
            group.setdefault("hooks", []).append(entry)
            return 1
    group = {"hooks": [entry]}
    if matcher:
        group["matcher"] = matcher
    groups.append(group)
    return 1


def install(host, root, settings_path_override=None):
    target = TARGETS[host]  # KeyError for an unknown host is the intended behaviour
    path = settings_path_override or settings_path(host)
    data, existed = _load(path)
    backup = _backup(path) if existed else None

    hooks = data.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        raise ValueError("%s has a 'hooks' key that is not an object. clowk will not modify it." % path)

    added = _add(hooks, target["prompt_event"], None, _command(root, "hook_prompt.py", host), path)
    added += _add(hooks, target["tool_event"], target["tool_matcher"],
                  _command(root, "hook_pretool.py", host), path)

    _save(path, data)
    return {"settings": path, "backup": backup, "added": added}


def uninstall(host, settings_path_override=None):
    target = TARGETS[host]
    path = settings_path_override or settings_path(host)
    data, existed = _load(path)
    if not existed:
        return {"settings": path, "removed": 0}

    hooks = data.get("hooks")
    if not isinstance(hooks, dict):
        return {"settings": path, "removed": 0}

    removed = 0
    for event in (target["prompt_event"], target["tool_event"]):
        groups = hooks.get(event)
        if not isinstance(groups, list):
            continue
        kept_groups = []
        removed_here = 0
        for group in groups:
            if not isinstance(group, dict):
                kept_groups.append(group)
                continue
            entries = group.get("hooks", [])
            if not isinstance(entries, list):
                # Nothing of ours can be in there, and it must be carried over rather than
                # skipped: a bare `continue` would drop it, and a removal elsewhere in this
                # event then writes that deletion to disk.
                kept_groups.append(group)
                continue
            kept = [e for e in entries if not is_clowk_entry(e)]
            dropped = len(entries) - len(kept)
            if not dropped:
                # Nothing of ours in here, so leave the group byte-for-byte as the user wrote
                # it. Rewriting it would add a "hooks" key to a matcher-only group, and the
                # prune below would then delete a group clowk never touched.
                kept_groups.append(group)
                continue
            removed_here += dropped
            group["hooks"] = kept
            if kept:
                kept_groups.append(group)
        removed += removed_here
        if not removed_here:
            continue  # untouched event: do not rewrite or prune it
        if kept_groups:
            hooks[event] = kept_groups
        else:
            hooks.pop(event, None)

    if removed:
        _save(path, data)
    return {"settings": path, "removed": removed}
